spring:
  application:
    name: Previsao_do_Tempo

  datasource:
    url: jdbc:postgresql://${HOST_POSTGRES}/${NAME_POSTGRES}
    username: ${USERNAME_POSTGRES}
    password: ${PASSWORD_POSTGRES}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

weather:
  api:
    key: ${WEATHER_API_KEY}
    url: ${API_URL}
    url_now: ${API_URL_NOW}
    url_coordination: ${API_URL_COORDINATION}
